POST http://localhost:3001/api/persons/
content-type: application/json

{
    "name": "Arto Hellas",
    "number": "040-123456"
}
###

GET http://localhost:3001/api/persons/

###
DELETE http://localhost:3001/api/persons/1

###
PUT http://localhost:3001/api/persons/001acc77-6534-4aa0-8ace-b437677424a1
content-type: application/json

{
    "name": "rto Hellas",
    "number": "040-123456"
}