GET http://localhost:3001/api/blogs

###
POST http://localhost:3001/api/blogs HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Illvb25hIiwiaWQiOiI2NWY5YjE5ODY1MjhmY2EwMWRlYzA5YWUiLCJpYXQiOjE3MTMyMTA2NzR9.GzZcJ9ALxTwPhg1GYQg7259930eVG1EEDNJxCAmr6I0

{
    "author": "Yoona",
    "title": "no user",
    "url": "urlurlurl",
    "likes": 0
}

###
DELETE http://localhost:3001/api/blogs/661a9eefca21af86f4c15912 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Illvb25hIiwiaWQiOiI2NWY5YjE5ODY1MjhmY2EwMWRlYzA5YWUiLCJpYXQiOjE3MTMyMDkzOTF9.C8xYlhIwJNvxhTxk9Xj2sIX3eWkZvr-1AnhPKboNFKs

###
PUT http://localhost:3001/api/blogs/65f89d38fa079ecf9af70b28 HTTP/1.1
content-type: application/json

{"title":"test","author":"ziqiwang","url":"www.example.com","likes":2}

###
GET http://localhost:3001/api/users

### 
POST http://localhost:3001/api/users HTTP/1.1
content-type: application/json

{
    "username": "Yoona",
    "name": "You Wu",
    "password": "123"
}

###
POST http://localhost:3001/api/login HTTP/1.1
content-type: application/json

{
    "username": "Yoona",
    "password": "123"
}