GET http://localhost:3001/api/blogs

###
POST http://localhost:3001/api/blogs HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Illvb25hIiwiaWQiOiI2NWY5YjE5ODY1MjhmY2EwMWRlYzA5YWUiLCJpYXQiOjE3MTA5NTE5ODl9.HjM7cqDAvxINKtRrVBCPhF9_8JJ-w5dYRtuqy9AhpfE

{
    "author": "Yoona",
    "title": "testuserextractor",
    "url": "urlurlurl",
    "likes": 0,
    "user": "65f9b1986528fca01dec09ae"
}

###
DELETE http://localhost:3001/api/blogs/65fb2faa016acb2e2768e30f HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Illvb25hIiwiaWQiOiI2NWY5YjE5ODY1MjhmY2EwMWRlYzA5YWUiLCJpYXQiOjE3MTA5NTE5ODl9.HjM7cqDAvxINKtRrVBCPhF9_8JJ-w5dYRtuqy9AhpfE

###
PUT http://localhost:3001/api/blogs/65e59513ef16585229de91bb HTTP/1.1
content-type: application/json

{
    "title" : "new",
    "author": "ziqiwang",
    "url": "www.example.com",
    "likes": 1
}

###
GET http://localhost:3001/api/users

### 
POST http://localhost:3001/api/users HTTP/1.1
content-type: application/json

{
    "username": "Yoona",
    "name": "You Wu",
    "password": "123"
}

###
POST http://localhost:3001/api/login HTTP/1.1
content-type: application/json

{
    "username": "Yoona",
    "password": "123"
}